name: Build

on: workflow_dispatch

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15'
          cache: npm

      - name: Setup NPM cache
        uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          node docker/pack

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: '**/dist'
          key: build-artifacts-${{ github.sha }}
