name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --scope @directus/shared --scope @directus/format-title --scope @directus/extensions-sdk --scope @directus/docs --scope @directus/app
