name: Heap Test

on: workflow_dispatch

jobs:
  build:
    name: Heap Test
    runs-on: ubuntu-latest
    # env:
    #   NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15'
          cache: npm

      - name: Check free memory
        run: free -m

      - name: Check current heap limit
        run: node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'

      - name: Run
        run: node heap.js
