name: Heap Test

on: workflow_dispatch

jobs:
  build:
    name: Heap Test
    runs-on: ubuntu-latest
    # env:
    #   NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15'
          cache: npm

      - name: Run
        run: node heap.js
