name: Pull Request Merged

on:
  pull_request:
    types:
      - closed

jobs:
  add_merged_pr_to_milestone:
    name: Add merged PR to milestone
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      milestones: ${{ steps.get_milestones.outputs.data }}
    steps:
      - name: Get milestones
        uses: octokit/request-action@v2.x
        id: get_milestones
        with:
          route: GET /repos/{owner}/{repo}/milestones
          owner: azrikahar
          repo: directus

      - name: Fail job if no milestones found
        if: ${{ fromJSON(steps.get_milestones.outputs.data)[0] == null }}
        run: exit 1

      - name: Add milestone
        uses: octokit/request-action@v2.x
        id: add_milestone
        with:
          route: PATCH /repos/{owner}/{repo}/issues/{issue_number}
          owner: azrikahar
          repo: directus
          issue_number: ${{ github.event.pull_request.number }}
          milestone: ${{ fromJSON(steps.get_milestones.outputs.data)[0].number }}

  update_draft_release_notes_and_changelog:
    name: Update draft release notes draft and changelog
    # if: ${{ fromJSON(needs.add_merged_pr_to_milestone.outputs.milestones).length > 0 }}
    runs-on: ubuntu-latest
    needs:
      - add_merged_pr_to_milestone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'rijkvanzanten/changelog-generator'

      - name: Install dependencies
        run: npm ci

      - name: Grant executable permissions
        run: chmod +x ./index.js

      - name: Generate changelog
        run: ./index.js "${{ fromJSON(needs.add_merged_pr_to_milestone.outputs.milestones)[0].title }}"

      - run: cat "./output/${{ fromJSON(needs.add_merged_pr_to_milestone.outputs.milestones)[0].title }}.md"
